// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/12/2025, 12:22:14 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/plugins/**/*.{js,ts,mjs}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/composables/**/*.{js,ts,mjs}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/utils/**/*.{js,ts,mjs}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/user/Desktop/VAND_TEST_TranAnhKiet/DG-Nuxtjs/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;